Repository team-B-free/02-PayHere, pull requests merged in 2022-07, with the labels that each got.

#3 [Docs] PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ 세팅

#4 Chore/2
  .eslintrc.json
  .husky/_/husky.sh
  .husky/pre-commit
  package-lock.json
  package.json
  src/bin/www.js
  src/config/config.js
  src/config/winston.js
  src/controllers/exam/examController.js
  src/controllers/exam/examController.spec.js
  src/controllers/exam/examValidator.js
  src/index.js
  src/models/index.js
  src/routes/examRoute.js
  src/routes/index.js
  src/utils/response.js
  src/utils/responseData.js
  src/utils/responseMessage.js
  src/utils/statusCode.js
Labels: ⚙ 세팅

#6 Feat/5
  package.json
  src/config/payHere.ddl
  src/models/comment.js
  src/models/index.js
  src/models/moneybook.js
  src/models/moneybookDetail.js
  src/models/user.js
Labels: ⚙ 세팅, 📃 문서

#12 [Feat] 패키지 구조 변경
  .eslintrc.json
  src/controllers/exam/examController.js
  src/controllers/exam/examController.spec.js
  src/controllers/exam/examValidator.js
  src/controllers/moneybook/moneybookController.js
  src/controllers/moneybook_detail/moneybookDetailController.js
  src/controllers/user/userController.js
  src/modules/readme.md
  src/routes/examRoute.js
  src/routes/index.js
  src/routes/moneybook/index.js
  src/routes/moneybook_detail/index.js
  src/routes/user/index.js
Labels: ⚙ 세팅

#13 Feat/7
  package-lock.json
  package.json
  src/config/payHere.ddl
  src/config/redis.js
  src/controllers/user/userController.js
  src/index.js
  src/middlewares/auth.js
  src/models/user.js
  src/routes/user/index.js
  src/services/user/userService.js
  src/utils/constants.js
  src/utils/jwtUtil.js
  src/utils/responseData.js
  src/utils/responseMessage.js
  src/validations/user/userValidator.js
Labels: ✨ 기능

#15 Feat/10
  src/controllers/user/userController.js
  src/routes/user/index.js
  src/services/user/userService.js
  src/validations/user/userValidator.js
Labels: ✨ 기능

#18 Feat/16
  .gitignore
  src/controllers/moneybook/moneybookController.js
  src/controllers/moneybook_detail/moneybookDetailController.js
  src/controllers/user/userController.js
  src/index.js
  src/routes/index.js
  src/routes/moneybook/index.js
  src/routes/moneybook_detail/index.js
  src/services/README.md
  src/services/moneybook/moneybookService.js
  src/services/moneybook_detail/moneybookDetailService.js
  src/services/user/userService.js
  src/validations/moneybook/moneybookValidator.js
Labels: ✨ 기능

#19 Refactor/17
  package-lock.json
  src/controllers/user/userController.js
  src/routes/index.js
  src/routes/user/index.js
  src/services/user/userService.js
Labels: ♻️ 리팩토링

#20 Feat/8
  src/config/config.js
  src/config/payHere.ddl
  src/config/redis.js
  src/controllers/moneybook/moneybookController.js
  src/controllers/moneybook_detail/moneybookDetailController.js
  src/controllers/user/userController.js
  src/index.js
  src/middlewares/auth.js
  src/models/comment.js
  src/models/index.js
  src/models/moneybook.js
  src/models/moneybookDetail.js
  src/models/user.js
  src/modules/readme.md
  src/modules/time.js
  src/routes/index.js
  src/routes/moneybook/index.js
  src/routes/moneybook_detail/index.js
  src/routes/user/index.js
  src/services/README.md
  src/services/moneybook/moneybookService.js
  src/services/moneybook_detail/moneybookDetailService.js
  src/services/user/userService.js
  src/utils/constants.js
  src/utils/envUtil.js
  src/utils/jwtUtil.js
  src/utils/response.js
  src/utils/responseData.js
  src/utils/responseMessage.js
  src/utils/statusCode.js
  src/validations/user/userValidator.js
Labels: ✨ 기능

#25 Feat/8
  .prettierrc
  src/config/payHere.ddl
  src/controllers/comment/commentController.js
  src/controllers/moneybook_detail/moneybookDetailController.js
  src/controllers/user/userController.js
  src/middlewares/auth.js
  src/models/comment.js
  src/models/index.js
  src/models/moneybook.js
  src/models/moneybookDetail.js
  src/models/user.js
  src/modules/time.js
  src/routes/moneybook/index.js
  src/routes/moneybook_detail/index.js
  src/routes/user/index.js
  src/services/comment/commentService.js
  src/services/moneybook/moneybookService.js
  src/services/moneybook_detail/moneybookDetailService.js
  src/services/user/userService.js
  src/utils/jwtUtil.js
  src/utils/responseData.js
  src/utils/responseMessage.js
Labels: ✨ 기능

#27 Refactor/22
  .prettierrc
  Dockerfile
  src/controllers/user/userController.js
  src/index.js
  src/middlewares/joiErrorHandler.js
  src/routes/moneybook/index.js
  src/routes/moneybook_detail/index.js
  src/validations/comment/commentValidator.js
  src/validations/moneybook/moneybookValidator.js
  src/validations/moneybookDetail/moneybookDetailValidator.js
  src/validations/user/userValidator.js
Labels: ♻️ 리팩토링
